services:
  dnsmasq:
    container_name: dnsmasq
    build: .
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
    - ./dnsmasq.conf:/etc/dnsmasq.conf
    - ./netboot.tar.gz:/etc/netboot.tar.gz
    - ./preseed.cfg:/etc/preseed.cfg