services:
  dnsmasq:
    name: dnsmasq
    build: .
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
    - ./dnsmasq.conf:/etc/dnsmasq.conf
    - ./netboot.tar.gz:/etc/netboot.tar.gz
    - ./undionly.kpxe:/tftpboot/undionly.kpxe
    - ./preseed.cfg:/tftpboot/preseed.cfg